#ifndef CONSTANTS_H
#define CONSTANTS_H
#include "util.h"

#define DISCHARGING_BATTERY_COLOR COLOR_WHITE
#define FULL_BATTERY_COLOR COLOR_PURPLE
#define LOW_BATTERY_THRESHOLD (20)
#define LOW_BATTERY_COLOR COLOR_RED
#define CHARGING_BATTERY_COLOR COLOR_YELLOW
#define BAT_METER_SEGMENTS (20)

#define CPU_LOW_TEMP_COLOR COLOR_WHITE
#define CPU_MED_TEMP_THRESHOLD (70)
#define CPU_MED_TEMP_COLOR COLOR_GREEN
#define CPU_HIGH_TEMP_THRESHOLD (85)
#define CPU_HIGH_TEMP_COLOR COLOR_RED
#define CPU_METER_SEGMENTS (20)

#define GPU_LOW_TEMP_COLOR COLOR_WHITE
#define GPU_MED_TEMP_THRESHOLD (70)
#define GPU_MED_TEMP_COLOR COLOR_GREEN
#define GPU_HIGH_TEMP_THRESHOLD (85)
#define GPU_HIGH_TEMP_COLOR COLOR_RED
#define GPU_METER_SEGMENTS (20)

#define RAM_METER_SEGMENTS (20)
#define RAM_METER_COLOR COLOR_WHITE

#define VRAM_METER_SEGMENTS (20)
#define VRAM_METER_COLOR COLOR_WHITE
#endif
